microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /idpayranking/(.*)

  serviceAccount:
    create: false
    annotations: { }
    name: ""

  podAnnotations: { }

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  envConfig:
    MONGODB_DBNAME: "idpay"
    APPLICATIONINSIGHTS_ROLE_NAME: "idpayranking"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"

  envConfigMapExternals:
    idpay-common:
      TZ: TZ
    idpay-eventhub-00:
      KAFKA_BROKER: kafka_broker
      KAFKA_CONFIG_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_CONFIG_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_ONBOARDING_RANKING_REQUESTS_BROKER: kafka_broker
      KAFKA_ONBOARDING_RANKING_REQUESTS_TOPIC: idpay-onboarding-ranking-request
      KAFKA_EVALUATION_ONBOARDING_OUTCOME_TOPIC: idpay_onboarding_outcome_topic
    idpay-eventhub-01:
      KAFKA_ERRORS_BROKER: kafka_broker
      KAFKA_ERRORS_TOPIC: idpay_error_topic
      KAFKA_INITIATIVE_RANKING_BROKER: kafka_broker
      KAFKA_INITIATIVE_RANKING_TOPIC: idpay_rule_update_topic

  envSecret:
    #    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key
    MONGODB_URI: mongodb-connection-string
    KAFKA_ERRORS_SASL_JAAS_CONFIG: evh-idpay-errors-idpay-errors-producer-jaas-config-idpay-01
    KAFKA_ONBOARDING_RANKING_REQUESTS_SASL_JAAS_CONFIG: evh-idpay-onboarding-ranking-request-idpay-onboarding-ranking-request-consumer-jaas-config-idpay-00
    KAFKA_EVALUATION_ONBOARDING_RANKING_SASL_JAAS_CONFIG: evh-idpay-onboarding-outcome-idpay-onboarding-outcome-producer-jaas-config-idpay-00
    KAFKA_INITIATIVE_RANKING_SASL_JAAS_CONFIG: evh-idpay-rule-update-idpay-rule-update-consumer-jaas-config-idpay-01
    SERVICEBUS_NAMESPACE_ONBOARDING_CONNECTION_STRING: idpay-service-bus-ns-manager-sas-key
    SERVICEBUS_ONBOARDING_CONNECTION_STRING: idpay-onboarding-request-processor-sas-key
    INITIATIVE_BLOB_STORAGE_CONNECTION_STRING: initiative-storage-blob-connection-string
    RANKING_P7M_CERT: ranking-p7m-cert
    RANKING_P7M_KEY_PEM: ranking-p7m-key
    PDV_DECRYPT_API_KEY: pdv-api-key
    PDV_DECRYPT_BASE_URL: pdv_decrypt_base_url